---
- name: Reboot for NVIDIA driver
  ansible.builtin.reboot:
    reboot_timeout: 300
    msg: "Rebooting to load NVIDIA driver (nouveau blacklisted)"
  become: true
  listen: "Reboot for NVIDIA driver"

- name: Restart Docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
  become: true
  listen: "Restart Docker"
