all:
  children:
    proxmox:
      hosts:
        pve1:
          ansible_host: 10.10.15.18
          ansible_port: 22
    openbsd_firewalls:
      hosts:
        fw1:
          ansible_host: 10.10.15.1
          ansible_port: 22
    linode_vps:
      hosts:
        felix:
          ansible_host: 45.56.113.70
          ansible_port: 5344
    dns_servers:
      hosts:
        dns1:
          ansible_host: 10.10.15.10
          ansible_port: 22
  hosts:
    portanas:
      ansible_host: 10.10.15.4
      ansible_port: 5344
      ansible_user: deploy
