---
# Configure OpenBao secrets management server
- name: Configure OpenBao
  hosts: secrets_servers
  gather_facts: true
  become: true
  roles:
    - hostname
    - users
    - packages
    - openbao
