---
# WireGuard configuration for fw1 (jlo)

wireguard_peers:
  - name: portaptty
    public_key: "mgkSd6pEkIWK8HlJlkYkoBZltckI1RegJeVbOMi+mFA="
    allowed_ips: "10.10.16.2/32"
    persistent_keepalive: 0
  - name: portaphone
    public_key: "/Moaa5jW3PvvEhW1TnBNVye7OFzPToi5OJkNmbZGECw="
    allowed_ips: "10.10.16.3/32"
    persistent_keepalive: 0
